/**
 * Reason codes for phishing detection rules.
 */
export const PHISHING_CODES = {
  PHISH_IMPERSONATION_NEW_DOMAIN: "PHISH_IMPERSONATION_NEW_DOMAIN",
  PHISH_SUSPICIOUS_TLD_MINT_KEYWORD: "PHISH_SUSPICIOUS_TLD_MINT_KEYWORD",
  PHISH_KNOWN_MALICIOUS_DOMAIN: "PHISH_KNOWN_MALICIOUS_DOMAIN",
  DOMAIN_IMPERSONATION: "DOMAIN_IMPERSONATION",
  NEW_DOMAIN: "NEW_DOMAIN",
  WALLET_CONNECT_PATTERN: "WALLET_CONNECT_PATTERN",
  SUSPICIOUS_TLD: "SUSPICIOUS_TLD",
  MINT_KEYWORD: "MINT_KEYWORD",
  KNOWN_MALICIOUS: "KNOWN_MALICIOUS",
  DIRECT_IP_ACCESS: "DIRECT_IP_ACCESS",
  NEW_DOMAIN_WALLET_CONNECT: "NEW_DOMAIN_WALLET_CONNECT",
  HOMOGLYPH_ATTACK: "HOMOGLYPH_ATTACK",
  SUSPICIOUS_REDIRECT_CHAIN: "SUSPICIOUS_REDIRECT_CHAIN",
} as const;

/** Union type of all phishing reason codes. */
export type PhishingCode = typeof PHISHING_CODES[keyof typeof PHISHING_CODES];
