/** Stable Layer 3 Phase B transaction and signature reason codes. */
export const TRANSACTION_CODES = {
  UNLIMITED_APPROVAL: "TX_UNLIMITED_APPROVAL",
  UNKNOWN_SPENDER: "TX_UNKNOWN_SPENDER",
  SET_APPROVAL_FOR_ALL: "TX_SET_APPROVAL_FOR_ALL",
  PERMIT_SIGNATURE: "TX_PERMIT_SIGNATURE",
  KNOWN_MALICIOUS_CONTRACT: "TX_KNOWN_MALICIOUS_CONTRACT",
  SCAM_SIGNATURE_MATCH: "TX_SCAM_SIGNATURE_MATCH",
  MULTICALL_APPROVAL_AND_TRANSFER: "TX_MULTICALL_APPROVAL_AND_TRANSFER",
  UNKNOWN_CONTRACT_INTERACTION: "TX_UNKNOWN_CONTRACT_INTERACTION",
  NEW_RECIPIENT: "TX_NEW_RECIPIENT",
} as const;

export type TransactionCode = typeof TRANSACTION_CODES[keyof typeof TRANSACTION_CODES];
